#ifndef 21_3_MCBSP_OPERATION_H_
#define 21_3_MCBSP_OPERATION_H_

//Data Transfer Process of McBSPs
//Companding (Compressing and Expanding) Data
//Clocking and Framing Data
//Frame Phases
//McBSP Reception
//McBSP Transmission
//Interrupts and DMA Events Generated by a McBSP

#endif /* 21_3_MCBSP_OPERATION_H_ */
