#ifndef 21_10_MCBSP_EMULATION_AND_RESET_CONSIDERATIONS_H_
#define 21_10_MCBSP_EMULATION_AND_RESET_CONSIDERATIONS_H_

//McBSP Emulation Mode
//Resetting and Initializing McBSPs

#endif /* 21_10_MCBSP_EMULATION_AND_RESET_CONSIDERATIONS_H_ */
