#ifndef 3_2_SYSTEM_CONTROL_SYSTEM_CONTROL_FUNCTIONAL_DESCRIPTION_H_
#define 3_2_SYSTEM_CONTROL_SYSTEM_CONTROL_FUNCTIONAL_DESCRIPTION_H_

//device identification
//Device Configuration Registers



#endif /* 3_2_SYSTEM_CONTROL_SYSTEM_CONTROL_FUNCTIONAL_DESCRIPTION_H_ */
