#ifndef 23_4_USB_INITIALIZATION_AND_CONFIGURATION_H_
#define 23_4_USB_INITIALIZATION_AND_CONFIGURATION_H_

//Pin Configuration
//Endpoint Configuration

#endif /* 23_4_USB_INITIALIZATION_AND_CONFIGURATION_H_ */
